# Black Holes

## Light cannot escape from black holes

General relativity is the theory developed by Einstein that predicts the existence of black holes, "cosmic bod[ies] of extremely intense gravity from which nothing, not even light, can escape"[^1].

The general mathematical intuition behind light, or anything else, not being able to escape from black holes is actually surprising simple.

We all learn in high school that the length of the sides of a right-angled triangle is given by the Pythagorean theorem.

$$
\begin{equation}
c^2=a^2+b^2
\end{equation}
$$
However, (the positive square root of) the right hand side of the above equation can also be thought of as the shortest distance between two points in a 2D map, assuming the ground is flat. In this case, $a$ would be the horizontal distance and $b$ would be the vertical distance (or vice versa).

In other words, suppose I want to find the distance between where I'm sitting and the corner of the room. I am located at $(x_1,y_1,z_1)$ and the corner of the room is at $(x_2,y_2,z_2)$. Then, the distance I want can be calculated using the equation below.

$$
\begin{equation}
Distance=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2+(z_2-z_1)^2}
\end{equation}
$$
Written more like the Pythagorean theorem, it would look like
$$
\begin{equation}
Distance^2=(\Delta x)^2+(\Delta y)^2+(\Delta z)^2,
\end{equation}
$$
where the Greek capital delta $\Delta$ refers to how much a quantity has changed between two values.

In relativity, we consider the more general concept of a 'spacetime interval', denoted $ds^2$, a kind of distance measure. One example of a spacetime interval (although just a space interval in this case), adapted from the equation above, can be written

$$
\begin{equation}
ds^2=dx^2+dy^2+dz^2.
\end{equation}
$$

The equation above relates to flat space. However, Einstein, in his special theory of relativity (1905), incorporates time into our model, creating 'spacetime'.[^2]

$$
\begin{equation}
ds^2=-dt^2+dx^2+dy^2+dz^2.
\end{equation}
$$
The spacetime interval above can be seen as a way to compare different journeys in spacetime.[^3]

Spacetime is flat in special relativity, which does not incorporate gravity. Think of it as the universe, but with nothing in it.

In the general theory of relativity (1915), Einstein considers a curved spacetime.[^4] One of the spacetime intervals that solves Einstein's equations, called the Schwarzschild solution, is given below in simplified notation.

$$
\begin{equation}
ds^2 = -\left(1 - \frac{2M}{r}\right) dt^2 + \frac{dr^2}{\left(1 - \frac{2M}{r}\right)} + r^2 d\theta^2 + r^2 \sin^2 \theta\, d\phi^2
\end{equation}
$$
We have converted into 'spherical coordinates', so instead of using $x$, $y$ and $z$, we are now using a radial coordinate $r$ (think the radius of a circle), along with two angular coordinates called 'theta' $\theta$ and 'phi' $\phi$.^ In the spacetime interval, there is also the mass of an object of interest $M$.[^5]

In fact, this spacetime interval describes a simple case of a non-spinning non-electrically-charged black hole. Apart from $r=0$, which is the famous 'singularity' of a black hole, we can see that something interesting happens when $r<2M$.[^6]

When $r>2M$, the $-(1-\frac{2M}{r})$ term is negative and hence the behaviour is reminiscent of the special relativity case, where the $dt$ term is negative compared to other terms. When $r<2M$, both the $dt^2$ and $dr^2$ terms flip sign.

If the object of interest is a black hole, then $r=2M$ is called the event horizon, also known as the Schwarzchild radius in this context.

Since $r$ is a spatial term and $t$ is time term, it would be easy to say that space and time have switched places, but this would be inaccurate.

We have all had our own experiences with space and time. We can go backwards and forwards in space. We can travel somewhere, then travel back to where we started. However, our experience with time is different. Time only ever seems to go forward and never backward.

The main point of the argument is that past the $r=2M$ threshold, as we get closer to the black hole (the radius to the black hole $r$ decreases), our behaviour in space takes on a more time-like quality in that it can only ever go forward and never backward. This means we can only ever go forward into the centre of the black hole. Therefore, we have an explanation as to why "light cannot escape from black holes". Past the event horizon, light (or anything) can only move forward toward the singularity, just like how our everyday experience of time is that it can only ever go forward.[^7]

To be most accurate on what exactly is happening when $r<2M$, here is exactly how some of the experts put it.[^8]

Carroll (2022) writes that: "This behavior is sometimes expressed... as 'time and space swap roles inside the event horizon of a black hole.' No. What happens is that the coordinates $t$ and $r$ swap their roles. Coordinates are a human invention and you shouldn't confuse them with fundamental features of reality. Time is still time and space is still space, no matter where we are or what coordinate system we are employing."

Earlier, Carroll (2022) explains: "$t$ is the timelike coordinate, while $r$ is a spacelike coordinate. But inside the horizon, these signs flip... $t$ is now spacelike, and $r$ is timelike. Physically, once we're inside the Schwarzchild radius, moving to ever-smaller values of $r$ is not moving toward the center, it's moving toward the future."

Susskind and Cabannes (2024) put it this way: "The singularity at $r=0$ is not a place, it is a time! More accurately, it is not a single place but many places all on a time-like curve.

...once we got past the horizon, we cannot avoid eventually running into the singularity. Why? Because we cannot avoid the future... We can go around a place, but we cannot go around a time."^^

Later theories included electric charge and spin (angular momentum) into the analysis of black holes, but the fundamental conclusions regarding event horizons are the same.[^9]

^ We could have converted to spherical coordinates earlier.

For example, in the space-only equation,

$$
\begin{equation}
ds^2=dx^2+dy^2+dz^2
\\=dr^2 + r^2 d\theta^2 + r^2 \sin^2 \theta \, d\phi^2.
\end{equation}
$$

The specific transformation being made is
$$
\begin{equation}
x = r \sin \theta \cos \phi, \quad
y = r \sin \theta \sin \phi, \quad
z = r \cos \theta.
\end{equation}
$$

^^ The most precise way to describe what is going on is to define the words timelike and spacelike.

Timelike trajectories are trajectories that we normally consider to be physically possible - travelling less than or equal to the speed of light. Spacelike trajectories require travel faster than the speed of light. They are better understood when plotted on a [spacetime diagram](https://en.wikipedia.org/wiki/Spacetime_diagram).

Mathematics gives us more concrete conditions on these trajectories. For example, spacelike events correspond to

$$
\begin{equation}
dx^2+dy^2+dz^2>dt^2
\end{equation}
$$
in the special relativity equation.

## References

Carroll, S. The Biggest Ideas in the Universe Volume I: Space, Time and Motion. Oneworld, 2022.

Susskind, L., & Cabannes, A. General Relativity: The Theoretical Minimum. Penguin Books, 2024.

[^1]: [The Editors of Encyclopaedia Britannica (2025, April 3). black hole. Encyclopedia Britannica.](https://www.britannica.com/science/black-hole)

[^2]: [English translation](https://en.wikisource.org/wiki/On_the_Electrodynamics_of_Moving_Bodies)

[^3]: The structure of the equation above gives a hint as to how the twin paradox can be resolved. Because of the negative sign in front of the time component, two spacetime interval values could potentially be the same if someone travels very fast through space but very little in time, versus someone who travels very little through space and hence must travel much further in time.

[^4]: [English translation](https://en.wikisource.org/wiki/Translation:The_Field_Equations_of_Gravitation)

[^5]: The Schwarzchild solution doesn't necessary need to represent a black hole. An object's radius could be larger than its supposed event horizon, in which case it would not be a black hole.

[^6]: The analysis in the main body is cleaner if we transform into a different set of coordinates, called [Eddington-Finkelstein coordinates](https://en.wikipedia.org/wiki/Eddington%E2%80%93Finkelstein_coordinates), but the expression itself looks more intimidating.

The advantage is that it avoids the division by zero problem in the $dr^2$ term when $r$ is exactly equal to $2M$.

[^7]: There is a conjecture that black holes are the simplest macroscopic objects and they are fully defined by their charge, spin and mass (see the  [no-hair theorem](https://en.wikipedia.org/wiki/No-hair_theorem)).

[^8]: I should note that I put the author's publishing dates as a reference, but these details have been known for much longer.

[^9]: If the black hole you fall into has a large mass, you won't even notice that you're passing the event horizon (Carroll, 2022).